<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.sourceforge.pmd.it</groupId>
    <artifactId>auxclasspath-java-runtime</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <java.version>8</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <pmd.plugin.version>3.28.0</pmd.plugin.version>
    </properties>

    <build>
       <plugins>
           <plugin>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${pmd.plugin.version}</version>
                <configuration>
                    <targetJdk>${java.version}</targetJdk>
                    <rulesets>
                        <ruleset>custom-ruleset.xml</ruleset>
                    </rulesets>
                    <printFailingErrors>true</printFailingErrors>
                    <verbose>false</verbose>
                </configuration>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals><goal>check</goal></goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>useToolchainPlugin</id>
            <activation>
                <property>
                    <name>toolchain.jdk.version</name>
                </property>
            </activation>
            <build>
              <plugins>
                <plugin>
                  <artifactId>maven-toolchains-plugin</artifactId>
                  <version>3.3.0</version>
                  <executions>
                    <execution>
                      <goals>
                        <goal>toolchain</goal>
                      </goals>
                    </execution>
                  </executions>
                  <configuration>
                    <toolchains>
                      <jdk>
                        <version>${toolchain.jdk.version}</version>
                      </jdk>
                    </toolchains>
                  </configuration>
                </plugin>
              </plugins>
            </build>
        </profile>

        <profile>
            <id>usePmdToolchainConfig</id>
            <activation>
                <property>
                    <name>pmdToolchain.jdk.version</name>
                </property>
            </activation>
            <build>
              <plugins>
                  <plugin>
                        <artifactId>maven-pmd-plugin</artifactId>
                        <configuration>
                          <jdkToolchain>
                              <version>${pmdToolchain.jdk.version}</version>
                          </jdkToolchain>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
